include(CMakeParseArguments)

# Function to embed contents of a file as byte array in C/C++ header file(.h). The header file
# will contain a byte array and integer variable holding the size of the array.
# Parameters
#   SOURCE_FILE     - The path of source file whose contents will be embedded in the header file.
#   VARIABLE_NAME   - The name of the variable for the byte array. The string "_SIZE" will be append
#                     to this name and will be used a variable name for size variable.
#   HEADER_FILE     - The path of header file.
#   APPEND          - If specified appends to the header file instead of overwriting it
#   NULL_TERMINATE  - If specified a null byte(zero) will be append to the byte array. This will be
#                     useful if the source file is a text file and we want to use the file contents
#                     as string. But the size variable holds size of the byte array without this
#                     null byte.
# Usage:
#   bin2h(SOURCE_FILE "Logo.png" HEADER_FILE "Logo.h" VARIABLE_NAME "LOGO_PNG")
function(BIN2H)
    set(oneValueArgs SOURCE_FILE VARIABLE_NAME HEADER_FILE)
    cmake_parse_arguments(BIN2H "${options}" "${oneValueArgs}" "" ${ARGN})

    # reads source file contents as hex string
    file(READ ${BIN2H_SOURCE_FILE} hexString HEX)
    string(LENGTH ${hexString} hexStringLength)
    math(EXPR arraySize "${hexStringLength} / 2")

    # adds '0x' prefix and comma suffix before and after every byte respectively
    set(arrayValues "")
    foreach(byte RANGE 0 ${arraySize})
        string(SUBSTRING ${hexString} ${byte} 2 byteValue)
        set(arrayValues "${arrayValues}\\\\x${byteValue}")
    endforeach()
    # removes trailing comma
    string(REGEX REPLACE ", $" "" arrayValues ${arrayValues})

    # converts the variable name into proper C identifier
    string(MAKE_C_IDENTIFIER "${BIN2H_VARIABLE_NAME}" BIN2H_VARIABLE_NAME)
    string(TOLOWER "${BIN2H_VARIABLE_NAME}" BIN2H_VARIABLE_NAME)

    # header file generator
    math(EXPR offset "0")

    # add generated comment
    set(headerFile "/*\n * This file is generated by bin2h.cmake script.\n * Do not modify this file.\n */\n")

    # add variable declaration
    set(headerFile "${headerFile}\nconst unsigned char ${BIN2H_VARIABLE_NAME}[] =")

    while (hexStringLength GREATER 0)
        if (hexStringLength GREATER 32)
            math(EXPR length 32)
        else()
            math(EXPR length ${hexStringLength})
        endif()

        string(SUBSTRING ${hexString} ${offset} ${length} line)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "\\\\x\\1" line ${line})
        set(headerFile "${headerFile}\n\t\"${line}\"")

        math(EXPR hexStringLength "${hexStringLength} - ${length}")
        math(EXPR offset "${offset} + ${length}")
    endwhile()

    # semi-colon and new line
    set(headerFile "${headerFile}\;\n\n")

    # add size variable declaration
    set(headerFile "${headerFile}const size_t ${BIN2H_VARIABLE_NAME}_size = ${arraySize}\;\n")

    # writes the header file
    file(WRITE ${BIN2H_HEADER_FILE} ${headerFile})
endfunction()